-- CreateTable
CREATE TABLE "PipelineProject" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "projectNumber" TEXT,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT,
    "dealType" TEXT,
    "siteAcceptance" TEXT,
    "milestones" TEXT,
    "dueDiligence" TEXT,
    "civilPermittingTeam" TEXT,
    "architectTeam" TEXT,
    "asBuilts" TEXT,
    "altaTopo" TEXT,
    "geotech" TEXT,
    "phase1Testing" TEXT,
    "asbestosTesting" TEXT,
    "signageVendor" TEXT,
    "signResourcePm" TEXT,
    "sentTo7B" TEXT,
    "signageApprovedBy7B" TEXT,
    "testFitRequested" TEXT,
    "testFitCompleted" TEXT,
    "testFitApproved" TEXT,
    "loiExecuted" TEXT,
    "titleReceived" TEXT,
    "titleReviewed" TEXT,
    "sir" TEXT,
    "initialBudget" TEXT,
    "leaseExecuted" TEXT,
    "rentCommencementDate" TEXT,
    "powerApplicationSubmitted" TEXT,
    "designKickoffCall" TEXT,
    "designDocsApproved" TEXT,
    "planningSubmittal" TEXT,
    "planningApproved" TEXT,
    "rowPermitsApproved" TEXT,
    "cdKickoffCall" TEXT,
    "ispIntakeFormSent" TEXT,
    "cdSubmittedTo7B" TEXT,
    "approved7B" TEXT,
    "cdsSubmitted" TEXT,
    "healthSubmitted" TEXT,
    "outToBid" TEXT,
    "prebidMeeting" TEXT,
    "bidsDue" TEXT,
    "finalBudgetApproved" TEXT,
    "generalContractor" TEXT,
    "gcContractIssued" TEXT,
    "permitsIssued" TEXT,
    "constructionStart" TEXT,
    "turnoverCoo" TEXT,
    "openDate" TEXT,
    "planningApprovalProcess" TEXT,
    "buildingApprovalProcess" TEXT,
    "developmentNotes" TEXT,

    CONSTRAINT "PipelineProject_pkey" PRIMARY KEY ("id")
);
